# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
  - package-ecosystem: "nuget"
    directory: "/src/NSubstitute"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      nsubstitute_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "nuget"
    directory: "/tests/NSubstitute.Acceptance.Specs"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      nsubstitute_acceptance_specs_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "nuget"
    directory: "/tests/NSubstitute.Benchmarks"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      nsubstitute_benchmarks_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
