os: Visual Studio 2017
build: off

environment:
  matrix:
    - Configuration: Debug
    - Configuration: Release

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install      

before_test:
  - dotnet --info

test_script:
  - build/build.cmd All
